services:
    mariadb:
        image: mariadb
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        volumes:
            - ./mariadb_data:/var/lib/mysql
        networks:
            - backend_db
        healthcheck:
            test:
                [
                    "CMD",
                    "/usr/local/bin/healthcheck.sh",
                    "--connect",
                    "--innodb_initialized",
                ]
            interval: 5s
            timeout: 10s
            retries: 10
        restart: always

    backend:
        build:
            context: .
            dockerfile: fct-backend/Dockerfile
        container_name: backend
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_NAME: mydatabase
            DB_USER: user
            DB_PASSWORD: userpassword
        networks:
            - backend_db
            - frontend_backend
        ports:
            - "8080:8080"
        restart: on-failure:10

    frontend:
        build:
            context: .
            dockerfile: fct-frontend/Dockerfile
        container_name: frontend
        depends_on:
            - backend
        networks:
            - frontend_backend
        ports:
            - "80:80"
        restart: on-failure

networks:
    backend_db:
        driver: bridge
    frontend_backend:
        driver: bridge

volumes:
    mariadb_data:
        driver: local
