server:
    error:
        include-stacktrace: never
        include-message: always
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: ${SPRING_APPLICATION_NAME:fct-backend}
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:mydatabase}
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${DB_USER:user}
        password: ${DB_PASSWORD:userpassword}
    jpa:
        # database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MariaDBDialect
    h2:
        console:
            enabled: false
    sql:
        init:
            mode: always
            platform: mariadb

mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:joseevasquezbarboza@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true

rsa:
    private-key: ${RSA_PRIVATE_KEY:classpath:certs/private-key.pem}
    public-key: ${RSA_PUBLIC_KEY:classpath:certs/public-key.pem}

app:
    jwt:
        expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
    refresh-token:
        expiration-days: ${REFRESH_TOKEN_EXPIRATION_DAYS:7}
    verification:
        expiration: ${VERIFICATION_EXPIRATION:120}
