/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/addresses-api';
export * from './api/appointment-categories-api';
export * from './api/appointments-api';
export * from './api/default-api';
export * from './api/invoices-api';
export * from './api/line-items-api';
export * from './api/users-api';

