/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddAppointmentCategoryRequest } from '../models';
// @ts-ignore
import type { AppointmentCategory } from '../models';
// @ts-ignore
import type { ErrorMessage } from '../models';
// @ts-ignore
import type { UpdateAppointmentCategoryRequest } from '../models';
/**
 * AppointmentCategoriesApi - axios parameter creator
 * @export
 */
export const AppointmentCategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new appointment category
         * @param {AddAppointmentCategoryRequest} [addAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAppointmentCategory: async (addAppointmentCategoryRequest?: AddAppointmentCategoryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/appointment-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addAppointmentCategoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAppointmentCategory: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteAppointmentCategory', 'id', id)
            const localVarPath = `/appointment-categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all appointment categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAppointmentCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/appointment-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an appointment category by id
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppointmentCategoryById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAppointmentCategoryById', 'id', id)
            const localVarPath = `/appointment-categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {UpdateAppointmentCategoryRequest} [updateAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointmentCategory: async (id: number, updateAppointmentCategoryRequest?: UpdateAppointmentCategoryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAppointmentCategory', 'id', id)
            const localVarPath = `/appointment-categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAppointmentCategoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppointmentCategoriesApi - functional programming interface
 * @export
 */
export const AppointmentCategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppointmentCategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new appointment category
         * @param {AddAppointmentCategoryRequest} [addAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAppointmentCategory(addAppointmentCategoryRequest?: AddAppointmentCategoryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppointmentCategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAppointmentCategory(addAppointmentCategoryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentCategoriesApi.createAppointmentCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAppointmentCategory(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAppointmentCategory(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentCategoriesApi.deleteAppointmentCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all appointment categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAppointmentCategories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AppointmentCategory>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAppointmentCategories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentCategoriesApi.getAllAppointmentCategories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an appointment category by id
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAppointmentCategoryById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppointmentCategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAppointmentCategoryById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentCategoriesApi.getAppointmentCategoryById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {UpdateAppointmentCategoryRequest} [updateAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAppointmentCategory(id: number, updateAppointmentCategoryRequest?: UpdateAppointmentCategoryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppointmentCategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppointmentCategory(id, updateAppointmentCategoryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentCategoriesApi.updateAppointmentCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppointmentCategoriesApi - factory interface
 * @export
 */
export const AppointmentCategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppointmentCategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new appointment category
         * @param {AddAppointmentCategoryRequest} [addAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAppointmentCategory(addAppointmentCategoryRequest?: AddAppointmentCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory> {
            return localVarFp.createAppointmentCategory(addAppointmentCategoryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAppointmentCategory(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAppointmentCategory(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all appointment categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAppointmentCategories(options?: RawAxiosRequestConfig): AxiosPromise<Array<AppointmentCategory>> {
            return localVarFp.getAllAppointmentCategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an appointment category by id
         * @param {number} id ID of the appointment category to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppointmentCategoryById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory> {
            return localVarFp.getAppointmentCategoryById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an appointment category
         * @param {number} id ID of the appointment category to return
         * @param {UpdateAppointmentCategoryRequest} [updateAppointmentCategoryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointmentCategory(id: number, updateAppointmentCategoryRequest?: UpdateAppointmentCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory> {
            return localVarFp.updateAppointmentCategory(id, updateAppointmentCategoryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppointmentCategoriesApi - interface
 * @export
 * @interface AppointmentCategoriesApi
 */
export interface AppointmentCategoriesApiInterface {
    /**
     * 
     * @summary Create a new appointment category
     * @param {AddAppointmentCategoryRequest} [addAppointmentCategoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApiInterface
     */
    createAppointmentCategory(addAppointmentCategoryRequest?: AddAppointmentCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory>;

    /**
     * 
     * @summary Delete an appointment category
     * @param {number} id ID of the appointment category to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApiInterface
     */
    deleteAppointmentCategory(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all appointment categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApiInterface
     */
    getAllAppointmentCategories(options?: RawAxiosRequestConfig): AxiosPromise<Array<AppointmentCategory>>;

    /**
     * 
     * @summary Get an appointment category by id
     * @param {number} id ID of the appointment category to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApiInterface
     */
    getAppointmentCategoryById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory>;

    /**
     * 
     * @summary Update an appointment category
     * @param {number} id ID of the appointment category to return
     * @param {UpdateAppointmentCategoryRequest} [updateAppointmentCategoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApiInterface
     */
    updateAppointmentCategory(id: number, updateAppointmentCategoryRequest?: UpdateAppointmentCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppointmentCategory>;

}

/**
 * AppointmentCategoriesApi - object-oriented interface
 * @export
 * @class AppointmentCategoriesApi
 * @extends {BaseAPI}
 */
export class AppointmentCategoriesApi extends BaseAPI implements AppointmentCategoriesApiInterface {
    /**
     * 
     * @summary Create a new appointment category
     * @param {AddAppointmentCategoryRequest} [addAppointmentCategoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApi
     */
    public createAppointmentCategory(addAppointmentCategoryRequest?: AddAppointmentCategoryRequest, options?: RawAxiosRequestConfig) {
        return AppointmentCategoriesApiFp(this.configuration).createAppointmentCategory(addAppointmentCategoryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an appointment category
     * @param {number} id ID of the appointment category to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApi
     */
    public deleteAppointmentCategory(id: number, options?: RawAxiosRequestConfig) {
        return AppointmentCategoriesApiFp(this.configuration).deleteAppointmentCategory(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all appointment categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApi
     */
    public getAllAppointmentCategories(options?: RawAxiosRequestConfig) {
        return AppointmentCategoriesApiFp(this.configuration).getAllAppointmentCategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an appointment category by id
     * @param {number} id ID of the appointment category to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApi
     */
    public getAppointmentCategoryById(id: number, options?: RawAxiosRequestConfig) {
        return AppointmentCategoriesApiFp(this.configuration).getAppointmentCategoryById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an appointment category
     * @param {number} id ID of the appointment category to return
     * @param {UpdateAppointmentCategoryRequest} [updateAppointmentCategoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentCategoriesApi
     */
    public updateAppointmentCategory(id: number, updateAppointmentCategoryRequest?: UpdateAppointmentCategoryRequest, options?: RawAxiosRequestConfig) {
        return AppointmentCategoriesApiFp(this.configuration).updateAppointmentCategory(id, updateAppointmentCategoryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

