/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddAppointmentRequest } from '../models';
// @ts-ignore
import type { Appointment } from '../models';
// @ts-ignore
import type { AppointmentStatusEnum } from '../models';
// @ts-ignore
import type { ErrorMessage } from '../models';
// @ts-ignore
import type { UpdateAppointmentRequest } from '../models';
// @ts-ignore
import type { UpdateAppointmentStatusRequest } from '../models';
// @ts-ignore
import type { ValidationErrorMessage } from '../models';
/**
 * AppointmentsApi - axios parameter creator
 * @export
 */
export const AppointmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new appointment
         * @param {AddAppointmentRequest} addAppointmentRequest Appointment to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAppointment: async (addAppointmentRequest: AddAppointmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addAppointmentRequest' is not null or undefined
            assertParamExists('addAppointment', 'addAppointmentRequest', addAppointmentRequest)
            const localVarPath = `/appointments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addAppointmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an appointment
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAppointment: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteAppointment', 'id', id)
            const localVarPath = `/appointments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all appointments
         * @param {number} [userId] Filter by user id
         * @param {AppointmentStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAppointments: async (userId?: number, status?: AppointmentStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/appointments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets all days with appointments from the current date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDaysWithAppointments: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/appointments/days`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an appointment by id
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppointmentById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAppointmentById', 'id', id)
            const localVarPath = `/appointments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an appointment
         * @param {number} id Appointment id
         * @param {UpdateAppointmentRequest} updateAppointmentRequest Appointment to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointment: async (id: number, updateAppointmentRequest: UpdateAppointmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAppointment', 'id', id)
            // verify required parameter 'updateAppointmentRequest' is not null or undefined
            assertParamExists('updateAppointment', 'updateAppointmentRequest', updateAppointmentRequest)
            const localVarPath = `/appointments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAppointmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an appointments status
         * @param {number} id Appointment id
         * @param {UpdateAppointmentStatusRequest} updateAppointmentStatusRequest Appointment status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointmentStatus: async (id: number, updateAppointmentStatusRequest: UpdateAppointmentStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAppointmentStatus', 'id', id)
            // verify required parameter 'updateAppointmentStatusRequest' is not null or undefined
            assertParamExists('updateAppointmentStatus', 'updateAppointmentStatusRequest', updateAppointmentStatusRequest)
            const localVarPath = `/appointments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAppointmentStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppointmentsApi - functional programming interface
 * @export
 */
export const AppointmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppointmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a new appointment
         * @param {AddAppointmentRequest} addAppointmentRequest Appointment to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAppointment(addAppointmentRequest: AddAppointmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Appointment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAppointment(addAppointmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.addAppointment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an appointment
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAppointment(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAppointment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.deleteAppointment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all appointments
         * @param {number} [userId] Filter by user id
         * @param {AppointmentStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAppointments(userId?: number, status?: AppointmentStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Appointment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAppointments(userId, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.getAllAppointments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets all days with appointments from the current date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDaysWithAppointments(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDaysWithAppointments(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.getAllDaysWithAppointments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an appointment by id
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAppointmentById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Appointment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAppointmentById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.getAppointmentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an appointment
         * @param {number} id Appointment id
         * @param {UpdateAppointmentRequest} updateAppointmentRequest Appointment to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAppointment(id: number, updateAppointmentRequest: UpdateAppointmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Appointment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppointment(id, updateAppointmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.updateAppointment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an appointments status
         * @param {number} id Appointment id
         * @param {UpdateAppointmentStatusRequest} updateAppointmentStatusRequest Appointment status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAppointmentStatus(id: number, updateAppointmentStatusRequest: UpdateAppointmentStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Appointment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppointmentStatus(id, updateAppointmentStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppointmentsApi.updateAppointmentStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppointmentsApi - factory interface
 * @export
 */
export const AppointmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppointmentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a new appointment
         * @param {AddAppointmentRequest} addAppointmentRequest Appointment to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAppointment(addAppointmentRequest: AddAppointmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment> {
            return localVarFp.addAppointment(addAppointmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an appointment
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAppointment(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAppointment(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all appointments
         * @param {number} [userId] Filter by user id
         * @param {AppointmentStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAppointments(userId?: number, status?: AppointmentStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<Appointment>> {
            return localVarFp.getAllAppointments(userId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets all days with appointments from the current date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDaysWithAppointments(options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.getAllDaysWithAppointments(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an appointment by id
         * @param {number} id Appointment id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppointmentById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Appointment> {
            return localVarFp.getAppointmentById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an appointment
         * @param {number} id Appointment id
         * @param {UpdateAppointmentRequest} updateAppointmentRequest Appointment to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointment(id: number, updateAppointmentRequest: UpdateAppointmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment> {
            return localVarFp.updateAppointment(id, updateAppointmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an appointments status
         * @param {number} id Appointment id
         * @param {UpdateAppointmentStatusRequest} updateAppointmentStatusRequest Appointment status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppointmentStatus(id: number, updateAppointmentStatusRequest: UpdateAppointmentStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment> {
            return localVarFp.updateAppointmentStatus(id, updateAppointmentStatusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppointmentsApi - interface
 * @export
 * @interface AppointmentsApi
 */
export interface AppointmentsApiInterface {
    /**
     * 
     * @summary Add a new appointment
     * @param {AddAppointmentRequest} addAppointmentRequest Appointment to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    addAppointment(addAppointmentRequest: AddAppointmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment>;

    /**
     * 
     * @summary Delete an appointment
     * @param {number} id Appointment id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    deleteAppointment(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all appointments
     * @param {number} [userId] Filter by user id
     * @param {AppointmentStatusEnum} [status] Filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    getAllAppointments(userId?: number, status?: AppointmentStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<Appointment>>;

    /**
     * 
     * @summary Gets all days with appointments from the current date
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    getAllDaysWithAppointments(options?: RawAxiosRequestConfig): AxiosPromise<Array<string>>;

    /**
     * 
     * @summary Get an appointment by id
     * @param {number} id Appointment id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    getAppointmentById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Appointment>;

    /**
     * 
     * @summary Update an appointment
     * @param {number} id Appointment id
     * @param {UpdateAppointmentRequest} updateAppointmentRequest Appointment to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    updateAppointment(id: number, updateAppointmentRequest: UpdateAppointmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment>;

    /**
     * 
     * @summary Update an appointments status
     * @param {number} id Appointment id
     * @param {UpdateAppointmentStatusRequest} updateAppointmentStatusRequest Appointment status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApiInterface
     */
    updateAppointmentStatus(id: number, updateAppointmentStatusRequest: UpdateAppointmentStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Appointment>;

}

/**
 * AppointmentsApi - object-oriented interface
 * @export
 * @class AppointmentsApi
 * @extends {BaseAPI}
 */
export class AppointmentsApi extends BaseAPI implements AppointmentsApiInterface {
    /**
     * 
     * @summary Add a new appointment
     * @param {AddAppointmentRequest} addAppointmentRequest Appointment to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public addAppointment(addAppointmentRequest: AddAppointmentRequest, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).addAppointment(addAppointmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an appointment
     * @param {number} id Appointment id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public deleteAppointment(id: number, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).deleteAppointment(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all appointments
     * @param {number} [userId] Filter by user id
     * @param {AppointmentStatusEnum} [status] Filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public getAllAppointments(userId?: number, status?: AppointmentStatusEnum, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).getAllAppointments(userId, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets all days with appointments from the current date
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public getAllDaysWithAppointments(options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).getAllDaysWithAppointments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an appointment by id
     * @param {number} id Appointment id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public getAppointmentById(id: number, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).getAppointmentById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an appointment
     * @param {number} id Appointment id
     * @param {UpdateAppointmentRequest} updateAppointmentRequest Appointment to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public updateAppointment(id: number, updateAppointmentRequest: UpdateAppointmentRequest, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).updateAppointment(id, updateAppointmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an appointments status
     * @param {number} id Appointment id
     * @param {UpdateAppointmentStatusRequest} updateAppointmentStatusRequest Appointment status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppointmentsApi
     */
    public updateAppointmentStatus(id: number, updateAppointmentStatusRequest: UpdateAppointmentStatusRequest, options?: RawAxiosRequestConfig) {
        return AppointmentsApiFp(this.configuration).updateAppointmentStatus(id, updateAppointmentStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

