/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddInvoiceRequest } from '../models';
// @ts-ignore
import type { ErrorMessage } from '../models';
// @ts-ignore
import type { Invoice } from '../models';
// @ts-ignore
import type { InvoiceStatusEnum } from '../models';
// @ts-ignore
import type { UpdateInvoiceRequest } from '../models';
// @ts-ignore
import type { UpdateInvoiceStatusRequest } from '../models';
// @ts-ignore
import type { ValidationErrorMessage } from '../models';
/**
 * InvoicesApi - axios parameter creator
 * @export
 */
export const InvoicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new invoice
         * @param {AddInvoiceRequest} addInvoiceRequest Invoice to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addInvoice: async (addInvoiceRequest: AddInvoiceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addInvoiceRequest' is not null or undefined
            assertParamExists('addInvoice', 'addInvoiceRequest', addInvoiceRequest)
            const localVarPath = `/invoice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addInvoiceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an invoice
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInvoice: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteInvoice', 'id', id)
            const localVarPath = `/invoice/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all invoices
         * @param {number} [userId] Filter by user id
         * @param {InvoiceStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllInvoices: async (userId?: number, status?: InvoiceStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an invoice by id
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInvoiceById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getInvoiceById', 'id', id)
            const localVarPath = `/invoice/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an invoice
         * @param {number} id Invoice id
         * @param {UpdateInvoiceRequest} updateInvoiceRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInvoice: async (id: number, updateInvoiceRequest: UpdateInvoiceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateInvoice', 'id', id)
            // verify required parameter 'updateInvoiceRequest' is not null or undefined
            assertParamExists('updateInvoice', 'updateInvoiceRequest', updateInvoiceRequest)
            const localVarPath = `/invoice/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateInvoiceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an invoice status
         * @param {number} id Invoice id
         * @param {UpdateInvoiceStatusRequest} updateInvoiceStatusRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInvoiceStatus: async (id: number, updateInvoiceStatusRequest: UpdateInvoiceStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateInvoiceStatus', 'id', id)
            // verify required parameter 'updateInvoiceStatusRequest' is not null or undefined
            assertParamExists('updateInvoiceStatus', 'updateInvoiceStatusRequest', updateInvoiceStatusRequest)
            const localVarPath = `/invoice/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateInvoiceStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoicesApi - functional programming interface
 * @export
 */
export const InvoicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvoicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a new invoice
         * @param {AddInvoiceRequest} addInvoiceRequest Invoice to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addInvoice(addInvoiceRequest: AddInvoiceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Invoice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addInvoice(addInvoiceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.addInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an invoice
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteInvoice(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteInvoice(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.deleteInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all invoices
         * @param {number} [userId] Filter by user id
         * @param {InvoiceStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllInvoices(userId?: number, status?: InvoiceStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Invoice>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllInvoices(userId, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.getAllInvoices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an invoice by id
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInvoiceById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Invoice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInvoiceById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.getInvoiceById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an invoice
         * @param {number} id Invoice id
         * @param {UpdateInvoiceRequest} updateInvoiceRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInvoice(id: number, updateInvoiceRequest: UpdateInvoiceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Invoice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateInvoice(id, updateInvoiceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.updateInvoice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an invoice status
         * @param {number} id Invoice id
         * @param {UpdateInvoiceStatusRequest} updateInvoiceStatusRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInvoiceStatus(id: number, updateInvoiceStatusRequest: UpdateInvoiceStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Invoice>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateInvoiceStatus(id, updateInvoiceStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicesApi.updateInvoiceStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvoicesApi - factory interface
 * @export
 */
export const InvoicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvoicesApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a new invoice
         * @param {AddInvoiceRequest} addInvoiceRequest Invoice to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addInvoice(addInvoiceRequest: AddInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice> {
            return localVarFp.addInvoice(addInvoiceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an invoice
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInvoice(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteInvoice(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all invoices
         * @param {number} [userId] Filter by user id
         * @param {InvoiceStatusEnum} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllInvoices(userId?: number, status?: InvoiceStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<Invoice>> {
            return localVarFp.getAllInvoices(userId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an invoice by id
         * @param {number} id Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInvoiceById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Invoice> {
            return localVarFp.getInvoiceById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an invoice
         * @param {number} id Invoice id
         * @param {UpdateInvoiceRequest} updateInvoiceRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInvoice(id: number, updateInvoiceRequest: UpdateInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice> {
            return localVarFp.updateInvoice(id, updateInvoiceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an invoice status
         * @param {number} id Invoice id
         * @param {UpdateInvoiceStatusRequest} updateInvoiceStatusRequest Invoice to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInvoiceStatus(id: number, updateInvoiceStatusRequest: UpdateInvoiceStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice> {
            return localVarFp.updateInvoiceStatus(id, updateInvoiceStatusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvoicesApi - interface
 * @export
 * @interface InvoicesApi
 */
export interface InvoicesApiInterface {
    /**
     * 
     * @summary Add a new invoice
     * @param {AddInvoiceRequest} addInvoiceRequest Invoice to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    addInvoice(addInvoiceRequest: AddInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice>;

    /**
     * 
     * @summary Delete an invoice
     * @param {number} id Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    deleteInvoice(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all invoices
     * @param {number} [userId] Filter by user id
     * @param {InvoiceStatusEnum} [status] Filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    getAllInvoices(userId?: number, status?: InvoiceStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<Invoice>>;

    /**
     * 
     * @summary Get an invoice by id
     * @param {number} id Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    getInvoiceById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Invoice>;

    /**
     * 
     * @summary Update an invoice
     * @param {number} id Invoice id
     * @param {UpdateInvoiceRequest} updateInvoiceRequest Invoice to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    updateInvoice(id: number, updateInvoiceRequest: UpdateInvoiceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice>;

    /**
     * 
     * @summary Update an invoice status
     * @param {number} id Invoice id
     * @param {UpdateInvoiceStatusRequest} updateInvoiceStatusRequest Invoice to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApiInterface
     */
    updateInvoiceStatus(id: number, updateInvoiceStatusRequest: UpdateInvoiceStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Invoice>;

}

/**
 * InvoicesApi - object-oriented interface
 * @export
 * @class InvoicesApi
 * @extends {BaseAPI}
 */
export class InvoicesApi extends BaseAPI implements InvoicesApiInterface {
    /**
     * 
     * @summary Add a new invoice
     * @param {AddInvoiceRequest} addInvoiceRequest Invoice to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public addInvoice(addInvoiceRequest: AddInvoiceRequest, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).addInvoice(addInvoiceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an invoice
     * @param {number} id Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public deleteInvoice(id: number, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).deleteInvoice(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all invoices
     * @param {number} [userId] Filter by user id
     * @param {InvoiceStatusEnum} [status] Filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public getAllInvoices(userId?: number, status?: InvoiceStatusEnum, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).getAllInvoices(userId, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an invoice by id
     * @param {number} id Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public getInvoiceById(id: number, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).getInvoiceById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an invoice
     * @param {number} id Invoice id
     * @param {UpdateInvoiceRequest} updateInvoiceRequest Invoice to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public updateInvoice(id: number, updateInvoiceRequest: UpdateInvoiceRequest, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).updateInvoice(id, updateInvoiceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an invoice status
     * @param {number} id Invoice id
     * @param {UpdateInvoiceStatusRequest} updateInvoiceStatusRequest Invoice to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public updateInvoiceStatus(id: number, updateInvoiceStatusRequest: UpdateInvoiceStatusRequest, options?: RawAxiosRequestConfig) {
        return InvoicesApiFp(this.configuration).updateInvoiceStatus(id, updateInvoiceStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

