/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddLineItemRequest } from '../models';
// @ts-ignore
import type { ErrorMessage } from '../models';
// @ts-ignore
import type { LineItem } from '../models';
// @ts-ignore
import type { ValidationErrorMessage } from '../models';
/**
 * LineItemsApi - axios parameter creator
 * @export
 */
export const LineItemsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add new line item
         * @param {AddLineItemRequest} addLineItemRequest Line item to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLineItem: async (addLineItemRequest: AddLineItemRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addLineItemRequest' is not null or undefined
            assertParamExists('addLineItem', 'addLineItemRequest', addLineItemRequest)
            const localVarPath = `/lineItem`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addLineItemRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLineItemById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteLineItemById', 'id', id)
            const localVarPath = `/lineItem/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all line items of an invoice
         * @param {number} [invoice] Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLineItems: async (invoice?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/lineItem`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (invoice !== undefined) {
                localVarQueryParameter['invoice'] = invoice;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLineItemById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getLineItemById', 'id', id)
            const localVarPath = `/lineItem/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LineItemsApi - functional programming interface
 * @export
 */
export const LineItemsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LineItemsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add new line item
         * @param {AddLineItemRequest} addLineItemRequest Line item to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLineItem(addLineItemRequest: AddLineItemRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LineItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLineItem(addLineItemRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LineItemsApi.addLineItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLineItemById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLineItemById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LineItemsApi.deleteLineItemById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all line items of an invoice
         * @param {number} [invoice] Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllLineItems(invoice?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LineItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllLineItems(invoice, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LineItemsApi.getAllLineItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLineItemById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LineItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLineItemById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LineItemsApi.getLineItemById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LineItemsApi - factory interface
 * @export
 */
export const LineItemsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LineItemsApiFp(configuration)
    return {
        /**
         * 
         * @summary Add new line item
         * @param {AddLineItemRequest} addLineItemRequest Line item to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLineItem(addLineItemRequest: AddLineItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<LineItem> {
            return localVarFp.addLineItem(addLineItemRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLineItemById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteLineItemById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all line items of an invoice
         * @param {number} [invoice] Invoice id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLineItems(invoice?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LineItem>> {
            return localVarFp.getAllLineItems(invoice, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a line item
         * @param {number} id Line item id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLineItemById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<LineItem> {
            return localVarFp.getLineItemById(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LineItemsApi - interface
 * @export
 * @interface LineItemsApi
 */
export interface LineItemsApiInterface {
    /**
     * 
     * @summary Add new line item
     * @param {AddLineItemRequest} addLineItemRequest Line item to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApiInterface
     */
    addLineItem(addLineItemRequest: AddLineItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<LineItem>;

    /**
     * 
     * @summary Delete a line item
     * @param {number} id Line item id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApiInterface
     */
    deleteLineItemById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all line items of an invoice
     * @param {number} [invoice] Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApiInterface
     */
    getAllLineItems(invoice?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LineItem>>;

    /**
     * 
     * @summary Get a line item
     * @param {number} id Line item id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApiInterface
     */
    getLineItemById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<LineItem>;

}

/**
 * LineItemsApi - object-oriented interface
 * @export
 * @class LineItemsApi
 * @extends {BaseAPI}
 */
export class LineItemsApi extends BaseAPI implements LineItemsApiInterface {
    /**
     * 
     * @summary Add new line item
     * @param {AddLineItemRequest} addLineItemRequest Line item to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApi
     */
    public addLineItem(addLineItemRequest: AddLineItemRequest, options?: RawAxiosRequestConfig) {
        return LineItemsApiFp(this.configuration).addLineItem(addLineItemRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a line item
     * @param {number} id Line item id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApi
     */
    public deleteLineItemById(id: number, options?: RawAxiosRequestConfig) {
        return LineItemsApiFp(this.configuration).deleteLineItemById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all line items of an invoice
     * @param {number} [invoice] Invoice id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApi
     */
    public getAllLineItems(invoice?: number, options?: RawAxiosRequestConfig) {
        return LineItemsApiFp(this.configuration).getAllLineItems(invoice, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a line item
     * @param {number} id Line item id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineItemsApi
     */
    public getLineItemById(id: number, options?: RawAxiosRequestConfig) {
        return LineItemsApiFp(this.configuration).getLineItemById(id, options).then((request) => request(this.axios, this.basePath));
    }
}

