/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddAppointmentRequest
 */
export interface AddAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof AddAppointmentRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AddAppointmentRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AddAppointmentRequest
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof AddAppointmentRequest
     */
    'duration': number;
    /**
     * 
     * @type {number}
     * @memberof AddAppointmentRequest
     */
    'userId': number;
    /**
     * 
     * @type {number}
     * @memberof AddAppointmentRequest
     */
    'categoryId': number;
}

