/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleEnum } from './role-enum';

/**
 * 
 * @export
 * @interface AddUserRequest
 */
export interface AddUserRequest {
    /**
     * 
     * @type {string}
     * @memberof AddUserRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequest
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequest
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequest
     */
    'password': string;
    /**
     * 
     * @type {RoleEnum}
     * @memberof AddUserRequest
     */
    'role': RoleEnum;
}



