/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddLineItemRequest
 */
export interface AddLineItemRequest {
    /**
     * 
     * @type {number}
     * @memberof AddLineItemRequest
     */
    'quantity': number;
    /**
     * 
     * @type {number}
     * @memberof AddLineItemRequest
     */
    'appointmentId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AddLineItemRequest
     */
    'productId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AddLineItemRequest
     */
    'invoiceId': number;
}

