/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceStatusEnum } from './invoice-status-enum';

/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'id': number;
    /**
     * 
     * @type {InvoiceStatusEnum}
     * @memberof Invoice
     */
    'status': InvoiceStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'paymentMethod': string;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'totalPrice': number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'userId': number;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'updatedAt': string;
}



