/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateAppointmentRequest
 */
export interface UpdateAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAppointmentRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAppointmentRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateAppointmentRequest
     */
    'duration'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateAppointmentRequest
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateAppointmentRequest
     */
    'categoryId'?: number;
}

