/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppointmentStatusEnum } from './appointment-status-enum';

/**
 * 
 * @export
 * @interface UpdateAppointmentStatusRequest
 */
export interface UpdateAppointmentStatusRequest {
    /**
     * 
     * @type {AppointmentStatusEnum}
     * @memberof UpdateAppointmentStatusRequest
     */
    'status': AppointmentStatusEnum;
}



