/* tslint:disable */
/* eslint-disable */
/**
 * REST API for the website of \"Academia Fabiana Perez\"
 * REST API for the website of \"Academia Fabiana Perez\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidationErrorMessage
 */
export interface ValidationErrorMessage {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorMessage
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof ValidationErrorMessage
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorMessage
     */
    'error': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ValidationErrorMessage
     */
    'messages': { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorMessage
     */
    'path': string;
}

